package UMSStudent;

import Exit.Exit;
import DBconnection.DatabaseConnection;
import UniversityManagementSystem.About;
import UniversityManagementSystem.Home;
import UniversityManagementSystem.Login;
import java.awt.BorderLayout;
import java.awt.Checkbox;
import java.awt.CheckboxGroup;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.TreePath;
import javax.swing.tree.TreeSelectionModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Naveen Rajasekara
 */
public class StudentChooser extends javax.swing.JFrame {

    /**
     * Creates new form StudentChooser
     */
    
    Connection connection = null;
    Statement statement = null;
    ResultSet resultSet = null;    
    
    public StudentChooser() {
        super("Student Enrolment");
        initComponents();
        connection = DatabaseConnection.connection();
    }
    
    public void showRecord() {
        try {
            statement = connection.createStatement();
            String sql = "SELECT Semester, Coursecode_and_Subject, Select_Courses FROM `enrolment` WHERE "
                    + "Year = 'Year I' , Faculty = 'Faculty of Science' ,Degree_programe = 'Bachelor of Science Honours in Software Engineering (SENG)'";
            resultSet = statement.executeQuery(sql);
            DefaultTableModel model = new DefaultTableModel()
            {
                public Class<?> getColumnClass(int column)
                {
                    switch(column)
                    {
                        case 0:
                            return String.class;
                        case 1:
                            return String.class;
                        case 2:
                            return Boolean.class;
                        default:
                            return String.class;
                    }
                }
            };

            //ASSIGN THE MODEL TO TABLE
            jTable1.setModel(model);

            model.addColumn("Semester");
            model.addColumn("Course");
            model.addColumn("Select Courses");
            
            int i = 0;
            while(resultSet.next()) {
                model.addRow(new Object[0]);
                model.setValueAt(resultSet.getString(1), i, 0);
                model.setValueAt(resultSet.getString(2), i, 1);
                model.setValueAt(resultSet.getBoolean(3),i,2);
                i++;
            }


        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        selectItem = new javax.swing.JButton();
        Faculty = new javax.swing.JComboBox<>();
        Degree = new javax.swing.JComboBox<>();
        Year = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Choose Your Path");

        selectItem.setBackground(new java.awt.Color(255, 255, 255));
        selectItem.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        selectItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/select.png"))); // NOI18N
        selectItem.setText("   Select");
        selectItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectItemActionPerformed(evt);
            }
        });

        Faculty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Faculty of Humenities", "Faculty of Social Science", "Faculty of Science", "Faculty of Commers and Management", "Faculty of Medicene", "Faculty of Computing and Technology", "Faculty of Graduate Studies" }));
        Faculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacultyActionPerformed(evt);
            }
        });

        Degree.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sinhala, Literary Criticism", "English Language and Literature", "Pali, Buddhist Culture, Buddhist Philosophy", "Sanskrit, Vastu Vidya", "Hindi", "French, German, Russian, Japanese,Chinese, Korean", "Linguistics, Translation Methods, Tamil,Tamil as a Second language", "Western Classical Culture, Christian Culture", "Teaching English as a Second language", "Drama and Theatre, Image Arts (Photography, Television and Cinema)", "Visual Arts (Arts, Computer Design),Performing Arts (Music, Dancing)", "B.A (General Degree) In Anthropology", "B.A (General Degree) In Archeology ", "B.A (special Degree) In Archeology ", "B.A (General Degree) In Tourism and Museum Management ", "B.A (special Degree) In Tourism and Museum Management ", "B.A (General Degree) In Economics ", "B.A (Special Degree) In Economics", "B.A. (General) Geography", "B.A. (Hons) Geography", "B.A. (General) Development Studies", "B.A. (Hons) Development Studies", "B.A. (General) History", "B.A. (Hons) History", "B.A. (General) in International Studies", "B.A.  (Honors) in International Studies", "B.A. (General) Degree Library and Information Science", "B.A. (Special) Degree Library and Information Science", "B.A. (General) Degree MACO ", "B.A. ( Special) Degree MACO", "B.A. (General) Degree PRMM", "B.A. ( Special) Degree PRMM", "B.A (General Degree) In Philosophy", "B.A (Special Degree) In Philosophy", "B.A (General Degree) In Political Science", "B.A (Special Degree) In Political Science", "B.A. (General) in Sociology", "B.A.  (Honours) in Sociology", "B.A. (General) Degree Social Statistics", "B.A. (Honours) Degree Social Statistics", "B.A (General) Degree Sport Science and Physical Education", "B.A (Special) Degree Sport Science and Physical Education", "Bachelor of Science Degree ", "Bachelor of Science Environmental Conservation and Management (ENCM)", "Bachelor of Science Physics and Electronics (PHEL)", "Bachelor of Science Honours in Biochemistry", "Bachelor of Science Honours in chemistry", "Bachelor of Science Honours in Computer Studies", "Bachelor of Science Honours in Information Technology", "Bachelor of Science Honours in Mathematical Physics", "Bachelor of Science Honours in Microbiology", "Bachelor of Science Honours in physics", "Bachelor of Science Honours in Statistics", "Bachelor of Science Honours in Botany", "Bachelor of Science Honours in Computer Science", "Bachelor of Science Honours in Environmental Conservation and Management (ENCM)", "Bachelor of Science Honours in Management and Information Technology (MIT)", "Bachelor of Science Honours in Mathematics", "Bachelor of Science Honours in Molecular Biology & Plant Biotechnology", "Bachelor of Science Honours in Software Engineering (SENG)", "Bachelor of Science Honours in Zoology", "Bachelor  of Commerce (Special) Degree in Commerce", "Bachelor  of Commerce (Special) Degree in Business Technology  ", "Bachelor  of Commerce (Special) Degree in Entrepreneurship", "Bachelor  of Commerce (Special) Degree in Financial  Management", "Bachelor  of Commerce (Special)  Degree External", "Bachelor  of Business Management (Special) Degree in Accountancy", "Bachelor  of Business Management (Special) Degree in Finance ", "Bachelor  of Business Management Honours in Financial Engineering", "Bachelor  of Business Management Honours in Insurance", "Bachelor  of Business Management Honours in Banking", "Bachelor  of Business Management (Special) Degree in Human Resource Management", "Bachelor  of Business Management (General) Degree External", "Bachelor  of Business Management (Special) Degree in Marketing ", "Bachelor of Medicine & Bachelor of Surgery", "Bachelor of Science (Speech & Hearing Sciences) ", "Bachelor of Science Honours in Computer Science Degree", "Bachelor of Engineering Technology (BET) Degree", "Bachelor of Information and Communication Technology (BICT) Degree" }));

        Year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year I", "Year II", "Year III", "Year IV" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Faculty : ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Degree Programe (Course) : ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Year :");

        jTable1.setModel(new DefaultTableModel());
        jTable1.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(408, 408, 408)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(416, 416, 416)
                        .addComponent(selectItem)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Year, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Degree, 0, 645, Short.MAX_VALUE)
                            .addComponent(Faculty, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(62, 62, 62))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Faculty, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Degree, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Year, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131)
                .addComponent(selectItem, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(245, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home.png"))); // NOI18N
        jMenuItem2.setText("Home");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        jMenuItem5.setText("Logout");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit2.png"))); // NOI18N
        jMenuItem6.setText("Exit");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("About");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/about.png"))); // NOI18N
        jMenuItem4.setText("About");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1062, 955));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        setVisible(false);
        About object = new About();
        object.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        setVisible(false);
        Exit exit = new Exit();
        exit.setExitPage(14);
        exit.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        setVisible(false);
        Login object = new Login();
        object.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        setVisible(false);
        Home object = new Home();
        object.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void selectItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectItemActionPerformed
        try {
            connection = DatabaseConnection.connection();
            statement = connection.createStatement();
            String sql = "SELECT semester, course_units, enroll FROM `degree&course_units` WHERE year = 'Year I'";
            resultSet = statement.executeQuery(sql);
            DefaultTableModel model = new DefaultTableModel()
            {
                public Class<?> getColumnClass(int column)
                {
                    switch(column)
                    {
                        case 0:
                            return String.class;
                        case 1:
                            return String.class;
                        case 2:
                            return Boolean.class;
                        default:
                            return String.class;
                    }
                }
            };

            //ASSIGN THE MODEL TO TABLE
            jTable1.setModel(model);

            model.addColumn("Semester");
            model.addColumn("Course");
            model.addColumn("Enroll");
            
            int i = 0;
            while(resultSet.next()) {
                model.addRow(new Object[0]);
                model.setValueAt(resultSet.getString(1), i, 0);
                model.setValueAt(resultSet.getString(2), i, 1);
                model.setValueAt(resultSet.getBoolean(3),i,2);
                i++;
            }


        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_selectItemActionPerformed

    private void FacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacultyActionPerformed
//        try {
//            connection = DatabaseConnection.connection();
//            statement = connection.createStatement();
//            String sql = "SELECT course_units FROM `degree&course_units` WHERE year = 'Year I'";
//            resultSet = statement.executeQuery(sql);
//            if(resultSet.next()){
//                setVisible(false);
//                Home object = new Home();
//                object.setVisible(true);
//            }
//            else{
//                JOptionPane.showMessageDialog(null, "Email or Password is Invalid");
//            }
//            
//        } catch (SQLException ex) {
//            Logger.getLogger(StudentChooser.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_FacultyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentChooser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Degree;
    private javax.swing.JComboBox<String> Faculty;
    private javax.swing.JComboBox<String> Year;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton selectItem;
    // End of variables declaration//GEN-END:variables
}
